In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

In [22]:
df=pd.read_csv("global_weather_clean.csv")

In [23]:
df.sample(5)

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,wind_kph,wind_degree,wind_direction,...,uv_index,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,month
3824,Nicaragua,Managua,12.1500,-86.2700,America/Managua,2024-06-03 08:15:00,31.0,3.6,10,N,...,7.0,323.80,25.0,4.700,6.900,6.500,8.600,1,1,6
36032,Russia,Moscow,55.7522,37.6156,Europe/Moscow,2024-11-18 11:45:00,4.1,19.1,213,SSW,...,0.4,638.25,37.0,40.885,21.275,25.715,26.085,2,3,11
37589,Portugal,Lisbon,38.7167,-9.1333,Europe/Lisbon,2024-11-26 09:00:00,12.2,7.9,89,E,...,0.2,371.85,12.0,70.670,7.770,47.360,60.495,3,5,11
52633,Bangladesh,Dhaka,23.7231,90.4086,Asia/Dhaka,2025-02-12 16:15:00,31.3,15.8,282,WNW,...,0.8,1122.95,75.0,31.635,32.930,115.440,118.400,4,10,2
75224,Azerbaijan,Baku,40.3953,49.8822,Asia/Baku,2025-06-08 12:45:00,26.1,14.4,316,NW,...,7.0,294.15,97.0,6.660,3.700,49.395,52.725,3,6,6

In [4]:
irrelevant_cols = [
    'temperature_fahrenheit', 'feels_like_fahrenheit',
    'wind_mph', 'gust_mph', 'gust_kph',
    'pressure_in', 'precip_in', 'visibility_miles',
    'condition_text', 'last_updated_epoch',
    'sunrise', 'sunset', 'moonrise', 'moonset',
    'moon_phase', 'moon_illumination'
]

In [5]:
df = df.drop(columns=irrelevant_cols)

In [6]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated,temperature_celsius,wind_kph,wind_degree,wind_direction,...,visibility_km,uv_index,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,16-05-2024 13:15,26.6,13.3,338,NNW,...,10.0,7.0,277.0,103.0,1.1,0.2,8.4,26.6,1,1
1,Albania,Tirana,41.33,19.82,Europe/Tirane,16-05-2024 10:45,19.0,11.2,320,NW,...,10.0,5.0,193.6,97.3,0.9,0.1,1.1,2.0,1,1
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,16-05-2024 09:45,23.0,15.1,280,W,...,10.0,5.0,540.7,12.2,65.1,13.4,10.4,18.4,1,1
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,16-05-2024 10:45,6.3,11.9,215,SW,...,2.0,2.0,170.2,64.4,1.6,0.2,0.7,0.9,1,1
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,16-05-2024 09:45,26.0,13.0,150,SSE,...,10.0,8.0,2964.0,19.0,72.7,31.5,183.4,262.3,5,10

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122186 entries, 0 to 122185
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122186 non-null  object
 1   location_name                 122186 non-null  object
 2   latitude                      122186 non-null  float64
 3   longitude                     122186 non-null  float64
 4   timezone                      122186 non-null  object
 5   last_updated                  122186 non-null  object
 6   temperature_celsius           122186 non-null  float64
 7   wind_kph                      122186 non-null  float64
 8   wind_degree                   122186 non-null  int64
 9   wind_direction                122186 non-null  object
 10  pressure_mb                   122186 non-null  int64
 11  precip_mm                     122186 non-null  float64
 12  humidity                      122186 non-null  int64
 13  cloud                         122186 non-null  int64
 14  feels_like_celsius            122186 non-null  float64
 15  visibility_km                 122186 non-null  float64
 16  uv_index                      122186 non-null  float64
 17  air_quality_Carbon_Monoxide   122186 non-null  float64
 18  air_quality_Ozone             122186 non-null  float64
 19  air_quality_Nitrogen_dioxide  122186 non-null  float64
 20  air_quality_Sulphur_dioxide   122186 non-null  float64
 21  air_quality_PM2.5             122186 non-null  float64
 22  air_quality_PM10              122186 non-null  float64
 23  air_quality_us-epa-index      122186 non-null  int64
 24  air_quality_gb-defra-index    122186 non-null  int64
dtypes: float64(14), int64(6), object(5)
memory usage: 23.3+ MB

In [8]:
df['last_updated'] = pd.to_datetime(df['last_updated'], format='%d-%m-%Y %H:%M')

In [9]:
df['country'] = df['country'].astype('category')
df['location_name'] = df['location_name'].astype('category')
df['timezone'] = df['timezone'].astype('category')
df['wind_direction'] = df['wind_direction'].astype('category')

In [10]:
df['humidity'] = df['humidity'].astype('int32')

In [11]:
df['temperature_celsius'] = df['temperature_celsius'].astype('float32')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122186 entries, 0 to 122185
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122186 non-null  category
 1   location_name                 122186 non-null  category
 2   latitude                      122186 non-null  float64
 3   longitude                     122186 non-null  float64
 4   timezone                      122186 non-null  category
 5   last_updated                  122186 non-null  datetime64[ns]
 6   temperature_celsius           122186 non-null  float32
 7   wind_kph                      122186 non-null  float64
 8   wind_degree                   122186 non-null  int64
 9   wind_direction                122186 non-null  category
 10  pressure_mb                   122186 non-null  int64
 11  precip_mm                     122186 non-null  float64
 12  humidity                      122186 non-null  int32
 13  cloud                         122186 non-null  int64
 14  feels_like_celsius            122186 non-null  float64
 15  visibility_km                 122186 non-null  float64
 16  uv_index                      122186 non-null  float64
 17  air_quality_Carbon_Monoxide   122186 non-null  float64
 18  air_quality_Ozone             122186 non-null  float64
 19  air_quality_Nitrogen_dioxide  122186 non-null  float64
 20  air_quality_Sulphur_dioxide   122186 non-null  float64
 21  air_quality_PM2.5             122186 non-null  float64
 22  air_quality_PM10              122186 non-null  float64
 23  air_quality_us-epa-index      122186 non-null  int64
 24  air_quality_gb-defra-index    122186 non-null  int64
dtypes: category(4), datetime64[ns](1), float32(1), float64(13), int32(1), int64(5)
memory usage: 19.5 MB

In [13]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated', 'temperature_celsius', 'wind_kph', 'wind_degree',
       'wind_direction', 'pressure_mb', 'precip_mm', 'humidity', 'cloud',
       'feels_like_celsius', 'visibility_km', 'uv_index',
       'air_quality_Carbon_Monoxide', 'air_quality_Ozone',
       'air_quality_Nitrogen_dioxide', 'air_quality_Sulphur_dioxide',
       'air_quality_PM2.5', 'air_quality_PM10', 'air_quality_us-epa-index',
       'air_quality_gb-defra-index'],
      dtype='object')

In [14]:
df.describe()

,latitude,longitude,last_updated,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,...,visibility_km,uv_index,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index
count,122186.000000,122186.000000,122186,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,...,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000,122186.000000
mean,19.190574,21.997199,2025-03-27 03:05:16.001014784,21.721785,13.006446,169.349958,1014.099848,0.137448,65.982674,39.983091,...,9.528920,3.479366,480.372194,59.200081,15.328350,10.757324,24.720752,49.464633,1.713961,2.643707
min,-41.300000,-175.200000,2024-05-16 01:45:00,-29.799999,3.600000,1.000000,947.000000,0.000000,2.000000,0.000000,...,0.000000,0.000000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000
25%,3.750000,-6.836100,2024-10-21 10:15:00,16.400000,6.500000,81.000000,1010.000000,0.000000,50.000000,0.000000,...,10.000000,0.200000,213.600000,39.000000,1.600000,1.050000,7.150000,10.150000,1.000000,1.000000
50%,17.250000,23.316700,2025-03-27 11:15:00,24.200001,11.200000,162.000000,1014.000000,0.000000,71.000000,30.000000,...,10.000000,2.200000,305.250000,56.000000,5.400000,2.450000,14.400000,20.350000,1.000000,2.000000
75%,40.400000,50.580000,2025-08-31 09:00:00,28.100000,18.000000,256.000000,1018.000000,0.030000,84.000000,75.000000,...,10.000000,6.000000,475.450000,75.000000,17.850000,8.695000,28.305000,42.400000,2.000000,3.000000
max,64.150000,179.220000,2026-02-04 20:00:00,49.200001,2963.200000,360.000000,3006.000000,42.240000,100.000000,100.000000,...,32.000000,16.300000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000
std,24.428310,65.791864,NaN,9.506613,11.923675,103.387280,10.650735,0.574633,24.035822,34.048441,...,2.659303,3.569808,788.581912,31.236678,24.436966,37.301124,38.097356,152.544489,0.953161,2.479856

In [15]:
df.shape

(122186, 25)

In [16]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated                    0
temperature_celsius             0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
precip_mm                       0
humidity                        0
cloud                           0
feels_like_celsius              0
visibility_km                   0
uv_index                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:

# Extract month from datetime
df['month'] = df['last_updated'].dt.month

# Compute monthly averages for key weather metrics
monthly_avg = df.groupby('month')[['temperature_celsius','precip_mm','humidity','wind_kph']].mean()

print(monthly_avg)

       temperature_celsius  precip_mm   humidity   wind_kph
month
1                16.072073   0.122429  70.341072  12.759308
2                17.123112   0.108035  67.042021  13.248340
3                20.095299   0.131084  64.144347  13.267721
4                21.965059   0.129513  63.027350  13.304376
5                23.960472   0.151895  62.313995  13.677898
6                25.704567   0.139808  60.891873  14.229203
7                26.019444   0.167213  62.319969  13.703657
8                25.747953   0.153617  62.942841  13.283117
9                24.248833   0.152977  66.219004  12.781039
10               21.602371   0.128500  68.864390  12.085967
11               18.894619   0.136274  70.247943  11.813584
12               17.002060   0.111179  70.591398  12.493656

In [19]:
# Group by country and compute averages

regional_avg = df.groupby('country', observed=False)[['temperature_celsius','precip_mm','humidity','wind_kph']].mean()
print(regional_avg.head())

             temperature_celsius  precip_mm   humidity   wind_kph
country
Afghanistan            19.669744   0.035605  24.950637   8.775955
Albania                20.453663   0.140175  55.124204   8.964331
Algeria                21.413876   0.046730  62.251994  13.034290
Andorra                10.027389   0.122452  62.487261   8.316083
Angola                 26.129459   0.027086  74.049363   9.355573

In [20]:
df.to_csv("global_weather_clean.csv", index=False)